from __future__ import annotations

import json
import logging
from json import JSONDecodeError
from typing import Any, Protocol

from pydantic import ValidationError

from app.domain.models import PersonaGenerationInput, PersonaGenerationOutput, PersonaProfile
from app.domain.persona_generation import UniversalFakePersonaGenerator
from app.domain.token_counter import TokenCountedResult, TokenCounterService
from app.infrastructure.responses_client import (
    LLMClientError,
    OpenAICompatibleClient,
    Transport,
    _payload_size,
    _response_to_payload,
    _sanitize_api_key,
    parse_enveloped_json_output,
)

logger = logging.getLogger(__name__)


class PersonaGeneratorClient(Protocol):
    def generate_persona(self, payload: PersonaGenerationInput) -> TokenCountedResult[PersonaGenerationOutput]:
        """Generate and validate a hidden persona profile from a structured input payload."""
        ...


class FakePersonaGeneratorClient:
    def __init__(
        self,
        generator: UniversalFakePersonaGenerator | None = None,
        token_counter: TokenCounterService | None = None,
    ) -> None:
        """Keep a universal local persona generator for local/dev and deterministic tests."""
        self._generator = generator or UniversalFakePersonaGenerator()
        self._token_counter = token_counter or TokenCounterService()

    def generate_persona(self, payload: PersonaGenerationInput) -> TokenCountedResult[PersonaGenerationOutput]:
        """Return a PersonaProfile using deterministic local rules instead of an external LLM."""
        persona = self._generator.generate(
            scenario=payload.scenario,
            persona_policy={
                **payload.persona_policy,
                **self._policy_overrides(payload),
            },
        )
        output = PersonaGenerationOutput(
            persona=persona,
            generation_notes="Persona generated by local fallback generator.",
            policy_coverage=["scenario", "persona_policy"],
            risk_flags=[],
        )
        input_tokens = self._token_counter.count_json(payload.model_dump(mode="json"))
        output_tokens = self._token_counter.count_json(output.model_dump(mode="json"))
        return TokenCountedResult(value=output, input_tokens=input_tokens, output_tokens=output_tokens)

    def _policy_overrides(self, payload: PersonaGenerationInput) -> dict[str, object]:
        """Project typed generation fields back into the legacy free-form policy shape."""
        overrides: dict[str, object] = {}
        if payload.allowed_roles:
            overrides["allowed_roles"] = payload.allowed_roles
        if payload.target_action:
            overrides["target_action"] = payload.target_action
        return overrides


class PersonaGenerationBusinessValidationError(ValueError):
    """Raised when provider JSON is valid but violates product business rules."""


class StructuredPersonaGeneratorClient(OpenAICompatibleClient):
    _openai_missing_message = "openai package is required for persona generator providers."

    def __init__(
        self,
        *,
        provider: str,
        base_url: str,
        api_key: str,
        folder_id: str | None = None,
        agent_id: str | None = None,
        model_or_agent_label: str | None = None,
        master_prompt: str | None = None,
        json_template: str | None = None,
        system_prompt: str | None = None,
        api_style: str = "responses",
        response_format: str = "json_schema",
        timeout_seconds: int = 30,
        max_retries: int = 1,
        fallback_client: PersonaGeneratorClient | None = None,
        transport: Transport | None = None,
        debug_payload_logging: bool = False,
        token_counter: TokenCounterService | None = None,
    ) -> None:
        """Configure a structured persona generator client for OpenAI-compatible providers."""
        super().__init__(
            base_url=base_url,
            api_key=api_key,
            model=model_or_agent_label,
            folder_id=folder_id,
            system_prompt=system_prompt,
            api_style=api_style,
            response_format=response_format,
            timeout_seconds=timeout_seconds,
            max_retries=max_retries,
            transport=transport,
            debug_payload_logging=debug_payload_logging,
        )
        self._provider = provider
        self._agent_id = agent_id
        self._model_or_agent_label = model_or_agent_label
        self._master_prompt = master_prompt
        self._json_template = json_template
        self._fallback_client = fallback_client
        self._token_counter = token_counter or TokenCounterService()

    def generate_persona(self, payload: PersonaGenerationInput) -> TokenCountedResult[PersonaGenerationOutput]:
        """Call the provider and validate its response as PersonaGenerationOutput."""
        last_error: Exception | None = None
        for attempt in range(self._max_retries + 1):
            retry_instruction = (
                "Return one JSON object only. No markdown. No commentary. "
                "Use PersonaGenerationOutput schema. "
                "Do not include legacy accounting fields: current_accounting_model, legal_form, "
                "tax_system, accounting_software, accounting_software_mode, primary_docs_owner."
            ) if attempt > 0 else ""
            request_payload = self._build_request_payload(payload, retry_instruction)
            metadata = self._safe_request_metadata(attempt=attempt + 1, request_payload=request_payload)
            logger.info("persona_generator_request %s", metadata)
            if self._debug_payload_logging:
                logger.debug("persona_generator_request_payload %s", request_payload)
            try:
                raw_response = _response_to_payload(self._transport(request_payload))
                output = parse_persona_generation_response(raw_response)
                validate_generated_persona(output, payload)
                input_tokens = self._token_counter.count_string(request_payload.get("input", ""))
                output_tokens = self._token_counter.count_json(output.model_dump(mode="json"))
                return TokenCountedResult(value=output, input_tokens=input_tokens, output_tokens=output_tokens)
            except (LLMClientError, ValidationError, JSONDecodeError, TimeoutError, PersonaGenerationBusinessValidationError) as error:
                last_error = error
                logger.warning("persona_generator_request_failed attempt=%s error=%s", attempt + 1, error)
            except Exception as error:
                last_error = error
                logger.warning(
                    "persona_generator_http_error attempt=%s status=%s error=%s",
                    attempt + 1,
                    getattr(error, "status_code", None),
                    error,
                )
        if self._fallback_client is not None:
            logger.warning("persona_generator_fallback_to_local reason=%s", last_error)
            return self._fallback_client.generate_persona(payload)
        raise LLMClientError(f"Persona generator request failed after retries: {last_error}") from last_error

    def _build_request_payload(self, payload: PersonaGenerationInput, retry_instruction: str) -> dict[str, Any]:
        """Build a provider request without secrets and with a strict output schema."""
        snapshot = payload.model_dump(mode="json")
        if retry_instruction:
            snapshot["retry_instruction"] = retry_instruction
        request_payload: dict[str, Any] = {
            "input": json.dumps(
                {
                    "client_persona_context": payload.persona_generation_context,
                    "generation_payload": snapshot,
                },
                ensure_ascii=False,
            ),
            "text": {
                "format": {
                    "type": "json_schema",
                    "name": "persona_generation_output",
                    "schema": PersonaGenerationOutput.model_json_schema(),
                    "strict": True,
                }
            },
        }
        if self._agent_id:
            request_payload["prompt"] = {"id": self._agent_id}
        else:
            request_payload["model"] = self._model_or_agent_label or "gpt-4.1-mini"
        if self._system_prompt:
            request_payload["system_prompt"] = self._system_prompt
        return request_payload

    def _safe_request_metadata(self, *, attempt: int, request_payload: dict[str, Any]) -> dict[str, object]:
        """Log only routing metadata and payload sizes, never raw prompts or API keys."""
        return {
            "provider": self._provider,
            "attempt": attempt,
            "endpoint_url": self.endpoint_url,
            "api_key": _sanitize_api_key(self._api_key),
            "folder_id_present": bool(self._folder_id),
            "agent_id_present": bool(self._agent_id),
            "model_or_agent_label": self._model_or_agent_label,
            "payload_size": _payload_size(request_payload),
        }

def parse_persona_generation_response(raw_payload: dict[str, Any] | str) -> PersonaGenerationOutput:
    """Parse known provider response envelopes into a strict PersonaGenerationOutput."""
    return parse_enveloped_json_output(
        raw_payload,
        model=PersonaGenerationOutput,
        direct_key="persona",
        no_output_message="Persona generator response does not contain structured text output.",
    )


def validate_generated_persona(
    output: PersonaGenerationOutput,
    input_payload: PersonaGenerationInput | None = None,
) -> PersonaProfile:
    """Return a generated persona only after Pydantic and business-rule validation."""
    persona = output.persona

    if persona.authority_level != "final_decider":
        raise PersonaGenerationBusinessValidationError("Generated persona must be a final_decider.")

    if input_payload is not None:
        allowed_roles = set(input_payload.allowed_roles or [])
        if allowed_roles and persona.role not in allowed_roles:
            raise PersonaGenerationBusinessValidationError("Generated persona role is outside allowed_roles.")

    if not persona.current_business_context.strip():
        raise PersonaGenerationBusinessValidationError("Generated persona must include current_business_context.")

    if not persona.current_solution.strip():
        raise PersonaGenerationBusinessValidationError("Generated persona must include current_solution.")

    if len(persona.alternative_solutions) < 2:
        raise PersonaGenerationBusinessValidationError("Generated persona must include at least two alternative_solutions.")

    alternatives_joined = " | ".join(solution.lower() for solution in persona.alternative_solutions)
    status_quo_markers = [
        "статус-кво",
        "ничего не менять",
        "как сейчас",
        "текущий процесс",
        "оставить текущ",
        "продолжать",
        "status quo",
        "status-quo",
    ]
    if not any(marker in alternatives_joined for marker in status_quo_markers):
        raise PersonaGenerationBusinessValidationError(
            "Generated persona alternative_solutions must include status quo."
        )

    if len(persona.information_gaps) < 2:
        raise PersonaGenerationBusinessValidationError("Generated persona must include information_gaps.")

    if len(persona.latent_pains) < 2:
        raise PersonaGenerationBusinessValidationError("Generated persona must include latent_pains.")

    if len(persona.typical_objections) < 2:
        raise PersonaGenerationBusinessValidationError("Generated persona must include typical_objections.")

    if len(persona.decision_criteria) < 3:
        raise PersonaGenerationBusinessValidationError("Generated persona must include decision_criteria.")

    if len(persona.hidden_constraints) < 1:
        raise PersonaGenerationBusinessValidationError("Generated persona must include hidden_constraints.")

    if len(persona.business_facts) < 2:
        raise PersonaGenerationBusinessValidationError("Generated persona must include business_facts.")

    if len(persona.cares_about) < 3:
        raise PersonaGenerationBusinessValidationError("Generated persona must include cares_about.")

    if len(persona.proof_sensitivity) < 2:
        raise PersonaGenerationBusinessValidationError("Generated persona must include proof_sensitivity.")

    if len(persona.call_scoring_criteria) < 3:
        raise PersonaGenerationBusinessValidationError("Generated persona must include call_scoring_criteria.")

    if not persona.communication_style.strip():
        raise PersonaGenerationBusinessValidationError("Generated persona must include communication_style.")

    return persona
