from __future__ import annotations

import json
import logging
from json import JSONDecodeError
from pathlib import Path
from typing import Any, Callable, Protocol

from pydantic import ValidationError

from app.domain.models import PersonaGenerationInput, PersonaGenerationOutput, PersonaProfile
from app.domain.persona_generation import UniversalFakePersonaGenerator
from app.infrastructure.llm_client import LLMClientError, _extract_json_object, _payload_size, _response_to_payload, _sanitize_api_key

logger = logging.getLogger(__name__)


class PersonaGeneratorClient(Protocol):
    def generate_persona(self, payload: PersonaGenerationInput) -> PersonaGenerationOutput:
        """Generate and validate a hidden persona profile from a structured input payload."""
        ...


class FakePersonaGeneratorClient:
    def __init__(self, generator: UniversalFakePersonaGenerator | None = None) -> None:
        """Keep a universal local persona generator for local/dev and deterministic tests."""
        self._generator = generator or UniversalFakePersonaGenerator()

    def generate_persona(self, payload: PersonaGenerationInput) -> PersonaGenerationOutput:
        """Return a PersonaProfile using deterministic local rules instead of an external LLM."""
        persona = self._generator.generate(
            scenario=payload.scenario,
            persona_policy={
                **payload.persona_policy,
                **self._policy_overrides(payload),
            },
        )
        return PersonaGenerationOutput(
            persona=persona,
            generation_notes="Persona generated by local fallback generator.",
            policy_coverage=["scenario", "persona_policy"],
            risk_flags=[],
        )

    def _policy_overrides(self, payload: PersonaGenerationInput) -> dict[str, object]:
        """Project typed generation fields back into the legacy free-form policy shape."""
        overrides: dict[str, object] = {}
        if payload.allowed_roles:
            overrides["allowed_roles"] = payload.allowed_roles
        if payload.target_action:
            overrides["target_action"] = payload.target_action
        return overrides


Transport = Callable[[dict[str, Any]], Any]


class PersonaGenerationBusinessValidationError(ValueError):
    """Raised when provider JSON is valid but violates product business rules."""


class StructuredPersonaGeneratorClient:
    def __init__(
        self,
        *,
        provider: str,
        base_url: str,
        api_key: str,
        folder_id: str | None = None,
        agent_id: str | None = None,
        model_or_agent_label: str | None = None,
        master_prompt: str | None = None,
        json_template: str | None = None,
        timeout_seconds: int = 30,
        max_retries: int = 1,
        fallback_client: PersonaGeneratorClient | None = None,
        transport: Transport | None = None,
        debug_payload_logging: bool = False,
    ) -> None:
        """Configure an OpenAI/Yandex-compatible structured persona generator client."""
        self._provider = provider
        self._base_url = base_url.rstrip("/")
        self._api_key = api_key
        self._folder_id = folder_id
        self._agent_id = agent_id
        self._model_or_agent_label = model_or_agent_label
        self._master_prompt = master_prompt
        self._json_template = json_template
        self._timeout_seconds = timeout_seconds
        self._max_retries = max_retries
        self._fallback_client = fallback_client
        self._transport = transport or self._default_transport
        self._debug_payload_logging = debug_payload_logging

    def generate_persona(self, payload: PersonaGenerationInput) -> PersonaGenerationOutput:
        """Call the provider and validate its response as PersonaGenerationOutput."""
        last_error: Exception | None = None
        for attempt in range(self._max_retries + 1):
            retry_instruction = "Return one JSON object only. No markdown. No commentary." if attempt > 0 else ""
            request_payload = self._build_request_payload(payload, retry_instruction)
            metadata = self._safe_request_metadata(attempt=attempt + 1, request_payload=request_payload)
            logger.info("persona_generator_request %s", metadata)
            if self._debug_payload_logging:
                logger.debug("persona_generator_request_payload %s", request_payload)
            try:
                raw_response = _response_to_payload(self._transport(request_payload))
                output = parse_persona_generation_response(raw_response)
                validate_generated_persona(output, payload)
                return output
            except (LLMClientError, ValidationError, JSONDecodeError, TimeoutError, PersonaGenerationBusinessValidationError) as error:
                last_error = error
                logger.warning("persona_generator_request_failed attempt=%s error=%s", attempt + 1, error)
            except Exception as error:
                last_error = error
                logger.warning(
                    "persona_generator_http_error attempt=%s status=%s error=%s",
                    attempt + 1,
                    getattr(error, "status_code", None),
                    error,
                )
        if self._fallback_client is not None:
            logger.warning("persona_generator_fallback_to_local reason=%s", last_error)
            return self._fallback_client.generate_persona(payload)
        raise LLMClientError(f"Persona generator request failed after retries: {last_error}") from last_error

    def _build_request_payload(self, payload: PersonaGenerationInput, retry_instruction: str) -> dict[str, Any]:
        """Build a provider request without secrets and with a strict output schema."""
        snapshot = payload.model_dump(mode="json")
        if retry_instruction:
            snapshot["retry_instruction"] = retry_instruction
        request_payload: dict[str, Any] = {
            "input": json.dumps(
                {
                    "business_context": payload.persona_generation_prompt,
                    "payload": snapshot,
                },
                ensure_ascii=False,
            ),
            "text": {
                "format": {
                    "type": "json_schema",
                    "name": "persona_generation_output",
                    "schema": PersonaGenerationOutput.model_json_schema(),
                    "strict": True,
                }
            },
        }
        if self._agent_id:
            request_payload["prompt"] = {"id": self._agent_id}
        else:
            request_payload["model"] = self._model_or_agent_label or "gpt-4.1-mini"
        return request_payload

    def _safe_request_metadata(self, *, attempt: int, request_payload: dict[str, Any]) -> dict[str, object]:
        """Log only routing metadata and payload sizes, never raw prompts or API keys."""
        return {
            "provider": self._provider,
            "attempt": attempt,
            "endpoint_url": self.endpoint_url,
            "api_key": _sanitize_api_key(self._api_key),
            "folder_id_present": bool(self._folder_id),
            "agent_id_present": bool(self._agent_id),
            "model_or_agent_label": self._model_or_agent_label,
            "payload_size": _payload_size(request_payload),
        }

    def _default_transport(self, request_payload: dict[str, Any]) -> Any:
        """Execute the responses API call through the optional OpenAI-compatible SDK."""
        try:
            from openai import OpenAI
        except ImportError as error:
            raise LLMClientError("openai package is required for persona generator providers.") from error

        client = OpenAI(
            api_key=self._api_key,
            base_url=self._base_url,
            project=self._folder_id,
            timeout=self._timeout_seconds,
        )
        return client.responses.create(**request_payload)

    @property
    def endpoint_url(self) -> str:
        """Return the provider endpoint used for sanitized request metadata."""
        return f"{self._base_url}/responses"


def parse_persona_generation_response(raw_payload: dict[str, Any] | str) -> PersonaGenerationOutput:
    """Parse known provider response envelopes into a strict PersonaGenerationOutput."""
    if isinstance(raw_payload, dict) and "persona" in raw_payload:
        return PersonaGenerationOutput.model_validate(raw_payload)
    if isinstance(raw_payload, dict):
        output_text = raw_payload.get("output_text")
        if isinstance(output_text, str):
            return PersonaGenerationOutput.model_validate_json(_extract_json_object(output_text))
        output = raw_payload.get("output")
        if isinstance(output, list):
            for item in output:
                if not isinstance(item, dict):
                    continue
                content = item.get("content")
                if isinstance(content, list):
                    for chunk in content:
                        if not isinstance(chunk, dict):
                            continue
                        text = chunk.get("text")
                        if isinstance(text, str):
                            return PersonaGenerationOutput.model_validate_json(_extract_json_object(text))
        alternatives = raw_payload.get("alternatives")
        if isinstance(alternatives, list) and alternatives:
            message = alternatives[0].get("message", {})
            text = message.get("text")
            if isinstance(text, str):
                return PersonaGenerationOutput.model_validate_json(_extract_json_object(text))
        raise LLMClientError("Persona generator response does not contain structured text output.")
    try:
        decoded = json.loads(raw_payload)
    except JSONDecodeError:
        return PersonaGenerationOutput.model_validate_json(_extract_json_object(raw_payload))
    return parse_persona_generation_response(decoded)


def validate_generated_persona(
    output: PersonaGenerationOutput,
    input_payload: PersonaGenerationInput | None = None,
) -> PersonaProfile:
    """Return a generated persona only after Pydantic and business-rule validation."""
    persona = output.persona
    if persona.authority_level != "final_decider":
        raise PersonaGenerationBusinessValidationError("Generated persona must be a final_decider.")
    if input_payload is not None:
        if input_payload.allowed_roles and persona.role not in set(input_payload.allowed_roles):
            raise PersonaGenerationBusinessValidationError("Generated persona role is outside allowed_roles.")
    if not persona.latent_pains:
        raise PersonaGenerationBusinessValidationError("Generated persona must include latent_pains.")
    if not persona.typical_objections:
        raise PersonaGenerationBusinessValidationError("Generated persona must include typical_objections.")
    if not persona.decision_criteria:
        raise PersonaGenerationBusinessValidationError("Generated persona must include decision_criteria.")
    if not persona.current_business_context.strip():
        raise PersonaGenerationBusinessValidationError("Generated persona must include current_business_context.")
    return persona


def _persona_generator_instructions() -> str:
    """Keep persona-generator responsibilities separate from dialogue simulation."""
    prompt_path = Path(__file__).resolve().parents[1] / "prompts" / "persona_generator.md"
    if prompt_path.exists():
        return prompt_path.read_text(encoding="utf-8")
    return (
        "Generate a hidden B2B client PersonaProfile for a sales training simulator. "
        "Use only the provided organization/training policy and scenario context. "
        "Return JSON matching the schema. Do not simulate dialogue turns. "
        "Do not include secrets, API keys, credentials, or raw internal notes. "
        "The persona is server-side hidden state and must be internally consistent."
    )
